modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Rover656/Expanded-Caves/issues"

[[mods]]
modId="expcaves"
version="${file.jarVersion}"
displayName="Expanded Caves"
displayURL="https://www.curseforge.com/minecraft/mc-mods/expanded-caves"
logoFile= "expcaves.png"
authors="Rover656, Polyvalord"
description='''
	Expanded Caves:
	Making the underground full of things to discover.

	Originally developed by Polyvalord. Rewritten and Maintained by Rover656.
'''

[[dependencies.expcaves]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.expcaves]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,)"
ordering="NONE"
side="BOTH"
